import Navbar from '@/components/global/Navbar';
import { getSingleType, getBlogBySlug } from '@/lib/strapi';


export async function generateMetadata({ params }) {
  const blog = await getBlogBySlug(params.slug);

  return {
    title: blog?.Title || "CrybroSecurity",
    description: blog?.Excerpt || "Generated by create next app",
  };
}

export default async function BlogsLayout({ children }) {


  return (
    <div className="container mx-auto p-4">
      <main>
        {children}
      </main>
    </div>
  );
}